"""Stage 19 — Remote Deploy service."""
import logging
from sqlalchemy.orm import Session
from fastapi import HTTPException
from app.models.topic import Topic
from app.models.pipeline import DraftSection
from app.models.remote import SSHServer
from app.services.remote_prereqs import require_stage_done, update_execution_status

logger = logging.getLogger(__name__)

_RSYNC_EXCLUDES = [
    "--exclude __pycache__/",
    "--exclude .git/",
    "--exclude '*.pyc'",
    "--exclude '*.bin'",
    "--exclude '*.pt'",
    "--exclude '*.safetensors'",
]


def _upsert_draft(topic_id: int, section_name: str, content: str, db: Session) -> DraftSection:
    existing = (
        db.query(DraftSection)
        .filter_by(topic_id=topic_id, section_name=section_name)
        .order_by(DraftSection.version.desc())
        .first()
    )
    version = (existing.version + 1) if existing else 1
    draft = DraftSection(topic_id=topic_id, section_name=section_name, content=content, version=version)
    db.add(draft)
    return draft


class RemoteDeployService:

    def generate_deploy_script(
        self, topic: Topic, server: SSHServer | None, db: Session
    ) -> DraftSection:
        require_stage_done(topic.id, "stage18", db)

        if server is None:
            raise HTTPException(400, detail="An SSH server must be selected before running this stage.")

        excludes_str = " \\\n  ".join(_RSYNC_EXCLUDES)
        remote_dir = f"~/experiments/topic_{topic.id}"

        lines = [
            "#!/usr/bin/env bash",
            "# Deploy script — generated by Remote Execution Stage 19",
            "# Set SSH_KEY_PATH before running: export SSH_KEY_PATH=/path/to/your/key",
            "",
            f"REMOTE_USER={server.username}",
            f"REMOTE_HOST={server.host}",
            f"REMOTE_DIR={remote_dir}",
            "",
            "# Create remote directory",
            f"ssh -i $SSH_KEY_PATH $REMOTE_USER@$REMOTE_HOST \"mkdir -p $REMOTE_DIR\"",
            "",
            "# Sync project files (excluding large/generated files)",
            f"rsync -avz --progress \\",
            f"  {excludes_str} \\",
            f"  ./ $REMOTE_USER@$REMOTE_HOST:$REMOTE_DIR/",
        ]

        if server.scheduler_type == "slurm":
            lines += [
                "",
                "# Slurm: create output and log directories",
                f"ssh -i $SSH_KEY_PATH $REMOTE_USER@$REMOTE_HOST \"mkdir -p $REMOTE_DIR/logs $REMOTE_DIR/checkpoints $REMOTE_DIR/results\"",
            ]

        lines += [
            "",
            "echo 'Deployment complete.'",
        ]

        content = "\n".join(lines)
        draft = _upsert_draft(topic.id, "deploy_script", content, db)
        db.commit()

        update_execution_status(topic.id, "deployed", db)

        logger.info("Stage 19 deploy script generated for topic %d (scheduler=%s)", topic.id, server.scheduler_type)
        return draft


remote_deploy_service = RemoteDeployService()
